# Generated by Django 4.2.2 on 2023-06-16 12:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('student_id', models.SmallIntegerField(max_length=100, primary_key=True, serialize=False)),
                ('student_name', models.CharField(max_length=100, unique=True)),
                ('DOB', models.DateField()),
                ('M_No', models.SmallIntegerField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_id', models.SmallIntegerField(max_length=10)),
                ('book_name', models.CharField(max_length=20)),
                ('checkout_date', models.DateField()),
                ('due_date', models.DateField()),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.student', unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_id', models.SmallIntegerField(max_length=10)),
                ('author_name', models.CharField(max_length=20)),
                ('book_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.book')),
            ],
        ),
    ]
